### ISSUE TITLE
Enhancement google bot

### ISSUE THREAD

**Issue by timerepubliksa** [wazeHQ/geo_redirect#17]
Hi, great plugin!

What do you think adding more options for search engine crawlers?

For example skipping redirect for bots. Or skipping redirect for certain user agents.
thank you

**Comment by afdev82** [comment]
More details about the idea? Maybe I could add this option.

**Comment by n0nick** [comment]
@afdev82 I think what would I would like here is to allow a `:skip_if` block that can run on each request and decide whether to skip GeoRedirect or not. Should be fairly easy to add.

**Comment by afdev82** [comment]
You think is it possible to define the block in the geo_redirect.yml configuration file and then call it in the GeoRedirect middleware?
I think I'm missing something here.

**Comment by n0nick** [comment]
not in geo_redirect.yml, but when including the middleware (i.e. similar to [how `exclude` and `include` are defined](https://github.com/wazeHQ/geo_redirect#scoping-redirects-for-certain-urls)).

e.g.
```ruby
Rails.application.middleware.use GeoRedirect::Middleware, skip_if: ->(req) { req.from_google_bot? }
```

**Comment by afdev82** [comment]
Yes, sorry I meant that...

**Comment by n0nick** [comment]
So yes, that's how the block is defined and then the middleware code can run this block (passing the request object as an argument) and decide based on its return value

**Comment by afdev82** [comment]
I wanted to try to use the [browser gem](https://github.com/fnando/browser) to check if it's a bot in the block.
I'll let you know, thanks! ;)

**Comment by afdev82** [comment]
I used the gem to get the required information:
`skip_if: ->(req) { Browser.new(ua: req.user_agent).search_engine? }`

**Comment by n0nick** [comment]
@timerepubliksa the new `skip_if` feature (implemented by @afdev82) can do the trick for you :)
