### ISSUE TITLE
Avoid to redirect some routes

### ISSUE THREAD

**Issue by rayoplateado** [wazeHQ/geo_redirect#18]
Is there a way to redirect all the traffic from a location, but not for the entire domain? So for example, i could redirect domain.com traffic except domain.com/pro traffic?

**Comment by n0nick** [comment]
@rayoplateado - yes, but not out-of-the-box.

GeoRedirect is a Rack middleware, and as such you can write a custom wrapper to achieve this.
See the following example (just replace `Deflater` with `GeoRedirect::Middleware `):
http://icelab.com.au/articles/wrapping-rack-middleware-to-exclude-certain-urls-for-rails-streaming-responses/

It will be a good idea to add an 'exclude' option to GeoRedirect, so I'll keep this issue open for now.

**Comment by n0nick** [comment]
So just to clarify, a wrapper can look like this:

```ruby
# lib/geo_redirect_with_exclude
class GeoRedirectWithExclude < GeoRedirect::Middleware
  def initialize(app, options = {})
    super
    @exclude = options[:exclude]
  end

  def call(env)
    if !@exclude.nil? && env['REQUEST_PATH'].match(@exclude)
      @app.call(env)
    else
      super
    end
  end
end
```

```ruby
# config/environments/production.rb
require 'geo_redirect_with_exclude'
Rails.application.middleware.use GeoRedirectWithExclude, exclude: '/pro'
```

(just a sketch, haven't tested this)

**Comment by rayoplateado** [comment]
Thanks for your answer.
Looks like exclude works, but now redirection doesn't.

I am working around of this, but here I paste what log is telling me.

```
F, [2015-07-13T06:48:20.861135 #19019] FATAL -- :
NoMethodError (undefined method '[]' for nil:NilClass): 
lib/geo_redirect_with_exclude.rb:15:in 'call'
```

This is my geo_redirect_with_exclude
```ruby
class GeoRedirectWithExclude < GeoRedirect::Middleware
  def initialize(app, options = {
    db: 'db/GeoIP.dat',
    config: 'config/georedirect.yml',
    logfile: 'log/geo_redirect_prod.log'
  })
    super
    @exclude = options[:exclude]
  end

  def call(env)
    if !@exclude.nil? && env['REQUEST_PATH'].match(@exclude)
      @app.call(env)
    else
      super
    end
  end
end
```

and this, my production.rb
```ruby
require 'geo_redirect_with_exclude'
  Rails.application.middleware.use GeoRedirectWithExclude, exclude: '/pro'
```
thanks!

**Comment by n0nick** [comment]
Not sure about the error, but note that in your production.rb, you start the middleware with `options == { exclude: '/pro' }`. It's not blank, so your default value (in geo_redirect_with_exclude.rb line 1) is not used.

So I would get rid of these values and pass the options in production.rb.

I'm not sure about the `NoMethodError` issue. Can you dig into the `@app.call(env)` line with a debugger and see where it fails inside GeoRedirect?

**Comment by rayoplateado** [comment]
Change the options to production.rb worked for me! Problem solved! Thanks for your help!!

**Comment by n0nick** [comment]
Glad to help :) I'll keep this issue open for now as a task to add an `exclude` option to the gem's middleware.

**Comment by n0nick** [comment]
FYI this is now done (see #19)
